FROM python:3.11-alpine3.17

RUN pip install Cython

RUN pip install --no-cache-dir --upgrade pip==26.0

RUN apk update --quiet \
    && apk -U upgrade libcrypto3 libssl3 --quiet \
    && apk add uchardet gcc g++ musl-dev --quiet \
    && apk upgrade --quiet

RUN pip install -U setuptools \
    && pip install --upgrade pip \
    && pip install --no-cache-dir --upgrade --force-reinstall "wheel==0.46.2"
